### ISSUE TITLE
credhub release bosh compilation requires internet access

### ISSUE THREAD

**Issue by poblin-orange** [pivotal-cf/credhub-release#42]
What version of the credhub server you are using?
 2.5.2

What version of the credhub cli you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

Attempting to bosh deploy a credhub server, on an internet air gaped environment.

What did you expect to happen?

Successfull bosh compilation, the deployment.

What was the actual behavior?

Compilation fails with the following stackrace

```
Task 4653997 | 14:02:54 | Preparing deployment: Preparing deployment (00:00:32)
Task 4653997 | 14:03:26 | Preparing deployment: Rendering templates (00:00:32)
Task 4653997 | 14:03:59 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 4653997 | 14:04:00 | Compiling packages: credhub/57aa502c13bc2eeed40edc2ba4cc2cda71e6fcbc (00:04:44)
                     L Error: Action Failed get_task: Task 42bacc30-8e67-45c9-5b9c-019eb01ba168 result: Compiling package credhub: Running packaging script: Running packaging script: Command exited with 1; Stdout: 
, Stderr: + export JAVA_HOME=/var/vcap/packages/openjdk_1.8.0/jre
+ JAVA_HOME=/var/vcap/packages/openjdk_1.8.0/jre
+ cd credhub
+ ./gradlew clean assemble
Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [ ] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by poblin-orange** [comment]
I just see that https://www.pivotaltracker.com/n/projects/1977341/stories/168380821 addresses the issue. Il bump. sorry for the noise
